
/*
 * File autogenerated by the test.
 */

#pragma once
/* The `platform.hh` should be created and include the specific platform header which will contain the device addresses.*/
#include  "platform.hh" 
#include  "mmio.hh" 
namespace mmio {
namespace i2c {

/* Interrupt State Register */
union IntrStateReg { 
    private:
      zermio::Register reg_;
    public:
    /* host mode interrupt: asserted whilst the FMT FIFO level is below the low threshold. This is a level status interrupt. */
    zermio::BitField<0, 1, zermio::Permissions::Read> fmt_threshold;
    /* host mode interrupt: asserted whilst the RX FIFO level is above the high threshold. This is a level status interrupt. */
    zermio::BitField<1, 1, zermio::Permissions::Read> rx_threshold;
    /* target mode interrupt: asserted whilst the ACQ FIFO level is above the high threshold. This is a level status interrupt. */
    zermio::BitField<2, 1, zermio::Permissions::Read> acq_threshold;
    /* host mode interrupt: raised if the RX FIFO has overflowed. */
    zermio::BitField<3, 1, zermio::Permissions::ReadWrite> rx_overflow;
    /* host mode interrupt: raised if the controller FSM is halted, such as on an unexpected NACK or lost arbitration.Check !!CONTROLLER_EVENTS for the reason.The interrupt will be released when the bits in !!CONTROLLER_EVENTS are cleared. */
    zermio::BitField<4, 1, zermio::Permissions::Read> controller_halt;
    /* host mode interrupt: raised if the SCL line drops early (not supported without clock synchronization). */
    zermio::BitField<5, 1, zermio::Permissions::ReadWrite> scl_interference;
    /* host mode interrupt: raised if the SDA line goes low when host is trying to assert high */
    zermio::BitField<6, 1, zermio::Permissions::ReadWrite> sda_interference;
    /* host mode interrupt: raised if target stretches the clock beyond the allowed timeout period */
    zermio::BitField<7, 1, zermio::Permissions::ReadWrite> stretch_timeout;
    /* host mode interrupt: raised if the target does not assert a constant value of SDA during transmission. */
    zermio::BitField<8, 1, zermio::Permissions::ReadWrite> sda_unstable;
    /* host and target mode interrupt.In host mode, raised if the host issues a repeated START or terminates the transaction by issuing STOP.In target mode, raised if the external host issues a STOP or repeated START. */
    zermio::BitField<9, 1, zermio::Permissions::ReadWrite> cmd_complete;
    /* target mode interrupt: raised if the target is stretching clocks for a read command. This is a level status interrupt. */
    zermio::BitField<10, 1, zermio::Permissions::Read> tx_stretch;
    /* target mode interrupt: asserted whilst the TX FIFO level is below the low threshold. This is a level status interrupt. */
    zermio::BitField<11, 1, zermio::Permissions::Read> tx_threshold;
    /* target mode interrupt: raised if the target is stretching clocks due to full ACQ FIFO or zero count in !!TARGET_ACK_CTRL.NBYTES (if enabled). This is a level status interrupt. */
    zermio::BitField<12, 1, zermio::Permissions::Read> acq_stretch;
    /* target mode interrupt: raised if STOP is received without a preceding NACK during an external host read. */
    zermio::BitField<13, 1, zermio::Permissions::ReadWrite> unexp_stop;
    /* target mode interrupt: raised if the host stops sending the clock during an ongoing transaction. */
    zermio::BitField<14, 1, zermio::Permissions::ReadWrite> host_timeout;
    constexpr IntrStateReg (uintptr_t addr): reg_{.addr = addr}
    {}

    inline void commit() { reg_.commit(); }

    inline IntrStateReg& fetch() {
        reg_.fetch();
        return *this;
    }
};



/* Interrupt Enable Register */
union IntrEnableReg { 
    private:
      zermio::Register reg_;
    public:
    /* Enable interrupt when !!INTR_STATE.fmt_threshold is set. */
    zermio::BitField<0, 1, zermio::Permissions::ReadWrite> fmt_threshold;
    /* Enable interrupt when !!INTR_STATE.rx_threshold is set. */
    zermio::BitField<1, 1, zermio::Permissions::ReadWrite> rx_threshold;
    /* Enable interrupt when !!INTR_STATE.acq_threshold is set. */
    zermio::BitField<2, 1, zermio::Permissions::ReadWrite> acq_threshold;
    /* Enable interrupt when !!INTR_STATE.rx_overflow is set. */
    zermio::BitField<3, 1, zermio::Permissions::ReadWrite> rx_overflow;
    /* Enable interrupt when !!INTR_STATE.controller_halt is set. */
    zermio::BitField<4, 1, zermio::Permissions::ReadWrite> controller_halt;
    /* Enable interrupt when !!INTR_STATE.scl_interference is set. */
    zermio::BitField<5, 1, zermio::Permissions::ReadWrite> scl_interference;
    /* Enable interrupt when !!INTR_STATE.sda_interference is set. */
    zermio::BitField<6, 1, zermio::Permissions::ReadWrite> sda_interference;
    /* Enable interrupt when !!INTR_STATE.stretch_timeout is set. */
    zermio::BitField<7, 1, zermio::Permissions::ReadWrite> stretch_timeout;
    /* Enable interrupt when !!INTR_STATE.sda_unstable is set. */
    zermio::BitField<8, 1, zermio::Permissions::ReadWrite> sda_unstable;
    /* Enable interrupt when !!INTR_STATE.cmd_complete is set. */
    zermio::BitField<9, 1, zermio::Permissions::ReadWrite> cmd_complete;
    /* Enable interrupt when !!INTR_STATE.tx_stretch is set. */
    zermio::BitField<10, 1, zermio::Permissions::ReadWrite> tx_stretch;
    /* Enable interrupt when !!INTR_STATE.tx_threshold is set. */
    zermio::BitField<11, 1, zermio::Permissions::ReadWrite> tx_threshold;
    /* Enable interrupt when !!INTR_STATE.acq_stretch is set. */
    zermio::BitField<12, 1, zermio::Permissions::ReadWrite> acq_stretch;
    /* Enable interrupt when !!INTR_STATE.unexp_stop is set. */
    zermio::BitField<13, 1, zermio::Permissions::ReadWrite> unexp_stop;
    /* Enable interrupt when !!INTR_STATE.host_timeout is set. */
    zermio::BitField<14, 1, zermio::Permissions::ReadWrite> host_timeout;
    constexpr IntrEnableReg (uintptr_t addr): reg_{.addr = addr}
    {}

    inline void commit() { reg_.commit(); }

    inline IntrEnableReg& fetch() {
        reg_.fetch();
        return *this;
    }
};



/* Interrupt Test Register */
union IntrTestReg { 
    private:
      zermio::Register reg_;
    public:
    /* Write 1 to force !!INTR_STATE.fmt_threshold to 1. */
    zermio::BitField<0, 1, zermio::Permissions::Write> fmt_threshold;
    /* Write 1 to force !!INTR_STATE.rx_threshold to 1. */
    zermio::BitField<1, 1, zermio::Permissions::Write> rx_threshold;
    /* Write 1 to force !!INTR_STATE.acq_threshold to 1. */
    zermio::BitField<2, 1, zermio::Permissions::Write> acq_threshold;
    /* Write 1 to force !!INTR_STATE.rx_overflow to 1. */
    zermio::BitField<3, 1, zermio::Permissions::Write> rx_overflow;
    /* Write 1 to force !!INTR_STATE.controller_halt to 1. */
    zermio::BitField<4, 1, zermio::Permissions::Write> controller_halt;
    /* Write 1 to force !!INTR_STATE.scl_interference to 1. */
    zermio::BitField<5, 1, zermio::Permissions::Write> scl_interference;
    /* Write 1 to force !!INTR_STATE.sda_interference to 1. */
    zermio::BitField<6, 1, zermio::Permissions::Write> sda_interference;
    /* Write 1 to force !!INTR_STATE.stretch_timeout to 1. */
    zermio::BitField<7, 1, zermio::Permissions::Write> stretch_timeout;
    /* Write 1 to force !!INTR_STATE.sda_unstable to 1. */
    zermio::BitField<8, 1, zermio::Permissions::Write> sda_unstable;
    /* Write 1 to force !!INTR_STATE.cmd_complete to 1. */
    zermio::BitField<9, 1, zermio::Permissions::Write> cmd_complete;
    /* Write 1 to force !!INTR_STATE.tx_stretch to 1. */
    zermio::BitField<10, 1, zermio::Permissions::Write> tx_stretch;
    /* Write 1 to force !!INTR_STATE.tx_threshold to 1. */
    zermio::BitField<11, 1, zermio::Permissions::Write> tx_threshold;
    /* Write 1 to force !!INTR_STATE.acq_stretch to 1. */
    zermio::BitField<12, 1, zermio::Permissions::Write> acq_stretch;
    /* Write 1 to force !!INTR_STATE.unexp_stop to 1. */
    zermio::BitField<13, 1, zermio::Permissions::Write> unexp_stop;
    /* Write 1 to force !!INTR_STATE.host_timeout to 1. */
    zermio::BitField<14, 1, zermio::Permissions::Write> host_timeout;
    constexpr IntrTestReg (uintptr_t addr): reg_{.addr = addr}
    {}

    inline void commit() { reg_.commit(); }

    inline IntrTestReg& fetch() {
        reg_.fetch();
        return *this;
    }
};



/* I2C Control Register */
union CtrlReg { 
    private:
      zermio::Register reg_;
    public:
    /* Enable Host I2C functionality */
    zermio::BitField<0, 1, zermio::Permissions::ReadWrite> enablehost;
    /* Enable Target I2C functionality */
    zermio::BitField<1, 1, zermio::Permissions::ReadWrite> enabletarget;
    /* Enable I2C line loopback testIf line loopback is enabled, the internal design sees ACQ and RX data as "1" */
    zermio::BitField<2, 1, zermio::Permissions::ReadWrite> llpbk;
    /* Enable NACKing the address on a stretch timeout.This is a Target mode feature.If enabled (1), a stretch timeout will cause the device to NACK the address byte.If disabled (0), a stretch timeout will cause the device to ACK the address byte.SMBus requires that devices always ACK their address, even for read commands.However, non-SMBus protocols may have a different approach and can choose to NACK instead.Note that both cases handle data bytes the same way.For writes, the Target module will NACK all subsequent data bytes until it receives a Stop.For reads, the Target module will release SDA, causing 0xff to be returned for all data bytes until it receives a Stop. */
    zermio::BitField<3, 1, zermio::Permissions::ReadWrite> nack_addr_after_timeout;
    /* Enable I2C Target ACK Control Mode.ACK Control Mode works together with !!TARGET_ACK_CTRL.NBYTES to allow software to control upper-layer protocol (N)ACKing (e.g. as in SMBus).This bit enables the mode when 1, and !!TARGET_ACK_CTRL.NBYTES limits how many bytes may be automatically ACK'd while the ACQ FIFO has space.If it is 0, the decision to ACK or NACK is made only from stretching timeouts and !!CTRL.NACK_ADDR_AFTER_TIMEOUT. */
    zermio::BitField<4, 1, zermio::Permissions::ReadWrite> ack_ctrl_en;
    /* Enable the bus monitor in multi-controller mode.If a 0->1 transition happens while !!CTRL.ENABLEHOST and !!CTRL.ENABLETARGET are both 0, the bus monitor will enable and begin in the "bus busy" state.To transition to a bus free state, !!HOST_TIMEOUT_CTRL must be nonzero, so the bus monitor may count out idle cycles to confirm the freedom to transmit.In addition, the bus monitor will track whether the bus is free based on the enabled timeouts and detected Stop symbols.For multi-controller mode, ensure !!CTRL.MULTI_CONTROLLER_MONITOR_EN becomes 1 no later than !!CTRL.ENABLEHOST or !!CTRL.ENABLETARGET.This bit can be set at the same time as either or both of the other two, though.Note that if !!CTRL.MULTI_CONTROLLER_MONITOR_EN is set after !!CTRL.ENABLEHOST or !!CTRL.ENABLETARGET, the bus monitor will begin in the "bus free" state instead.This would violate the proper protocol for a controller to join a multi-controller environment.However, if this controller is known to be the first to join, this ordering will enable skipping the idle wait.When 0, the bus monitor will report that the bus is always free, so the controller FSM is never blocked from transmitting. */
    zermio::BitField<5, 1, zermio::Permissions::ReadWrite> multi_controller_monitor_en;
    /* If set to 1, this bit causes a read transfer addressed to this target to set the corresponding bit in !!TARGET_EVENTS.While !!TARGET_EVENTS.TX_PENDING is 1, subsequent read transactions will stretch the clock, even if there is data in the TX FIFO.If enabled, this function allows software to confirm the data in the TX FIFO should be released for the current read.This may be useful for cases where the TX FIFO has data that does not apply to the current transfer.For example, the transaction could've targeted an alternate function via another address. */
    zermio::BitField<6, 1, zermio::Permissions::ReadWrite> tx_stretch_ctrl_en;
    constexpr CtrlReg (uintptr_t addr): reg_{.addr = addr}
    {}

    inline void commit() { reg_.commit(); }

    inline CtrlReg& fetch() {
        reg_.fetch();
        return *this;
    }
};



/* I2C Live Status Register for Host and Target modes */
union StatusReg { 
    private:
      zermio::Register reg_;
    public:
    /* Host mode FMT FIFO is full */
    zermio::BitField<0, 1, zermio::Permissions::Read> fmtfull;
    /* Host mode RX FIFO is full */
    zermio::BitField<1, 1, zermio::Permissions::Read> rxfull;
    /* Host mode FMT FIFO is empty */
    zermio::BitField<2, 1, zermio::Permissions::Read> fmtempty;
    /* Host functionality is idle. No Host transaction is in progress */
    zermio::BitField<3, 1, zermio::Permissions::Read> hostidle;
    /* Target functionality is idle. No Target transaction is in progress */
    zermio::BitField<4, 1, zermio::Permissions::Read> targetidle;
    /* Host mode RX FIFO is empty */
    zermio::BitField<5, 1, zermio::Permissions::Read> rxempty;
    /* Target mode TX FIFO is full */
    zermio::BitField<6, 1, zermio::Permissions::Read> txfull;
    /* Target mode receive FIFO is full */
    zermio::BitField<7, 1, zermio::Permissions::Read> acqfull;
    /* Target mode TX FIFO is empty */
    zermio::BitField<8, 1, zermio::Permissions::Read> txempty;
    /* Target mode receive FIFO is empty */
    zermio::BitField<9, 1, zermio::Permissions::Read> acqempty;
    /* Target mode stretching at (N)ACK phase due to zero count in !!TARGET_ACK_CTRL.NBYTES */
    zermio::BitField<10, 1, zermio::Permissions::Read> ack_ctrl_stretch;
    constexpr StatusReg (uintptr_t addr): reg_{.addr = addr}
    {}

    inline void commit() { reg_.commit(); }

    inline StatusReg& fetch() {
        reg_.fetch();
        return *this;
    }
};



/* I2C Read Data */
union RdataReg { 
    private:
      zermio::Register reg_;
    public:
    /*  */
    zermio::BitField<0, 8, zermio::Permissions::Read> rdata;
    constexpr RdataReg (uintptr_t addr): reg_{.addr = addr}
    {}

    inline void commit() { reg_.commit(); }

    inline RdataReg& fetch() {
        reg_.fetch();
        return *this;
    }
};



/* I2C Host Format DataWrites to this register are used to define and drive Controller-Mode transactions. */
union FdataReg { 
    private:
      zermio::Register reg_;
    public:
    /* Format Byte.If no flags are set, hardware will transmit this byte directly.If READB is set, this field becomes the number of bytes hardware will automaticallyread from the bus. */
    zermio::BitField<0, 8, zermio::Permissions::Write> fbyte;
    /* Issue a START condition before transmitting FBYTE. */
    zermio::BitField<8, 1, zermio::Permissions::Write> start;
    /* Issue a STOP condition after transmitting FBYTE. */
    zermio::BitField<9, 1, zermio::Permissions::Write> stop;
    /* Transfer Direction Indicator.If unset, this write to FDATA defines a controller-transmitter operation (WRITE).A single byte of data (FBYTE) is written to the bus.If set, this write to FDATA defines a controller-receiver operation (READ).The value of FBYTE defines the number of bytes read from the bus. (256 if FBYTE==0)"After this number of bytes are read, the final byte will be NACKed to end the transferunless RCONT is also set. */
    zermio::BitField<10, 1, zermio::Permissions::Write> readb;
    /* Do not NACK the last byte read, let the read operation continue. */
    zermio::BitField<11, 1, zermio::Permissions::Write> rcont;
    /* For the currrent controller-transmitter byte (WRITE), do not halt via CONTROLLER_EVENTSor assert the 'controller_halt' interrupt if the current byte is not ACK'd. */
    zermio::BitField<12, 1, zermio::Permissions::Write> nakok;
    constexpr FdataReg (uintptr_t addr): reg_{.addr = addr}
    {}

    inline void commit() { reg_.commit(); }

    inline FdataReg& fetch() {
        reg_.fetch();
        return *this;
    }
};



/* I2C FIFO control register */
union FifoCtrlReg { 
    private:
      zermio::Register reg_;
    public:
    /* RX fifo reset. Write 1 to the register resets RX_FIFO. Read returns 0 */
    zermio::BitField<0, 1, zermio::Permissions::Write> rxrst;
    /* FMT fifo reset. Write 1 to the register resets FMT_FIFO. Read returns 0 */
    zermio::BitField<1, 1, zermio::Permissions::Write> fmtrst;
    /* ACQ FIFO reset. Write 1 to the register resets it. Read returns 0 */
    zermio::BitField<7, 1, zermio::Permissions::Write> acqrst;
    /* TX FIFO reset. Write 1 to the register resets it. Read returns 0 */
    zermio::BitField<8, 1, zermio::Permissions::Write> txrst;
    constexpr FifoCtrlReg (uintptr_t addr): reg_{.addr = addr}
    {}

    inline void commit() { reg_.commit(); }

    inline FifoCtrlReg& fetch() {
        reg_.fetch();
        return *this;
    }
};



/* Host mode FIFO configuration */
union HostFifoConfigReg { 
    private:
      zermio::Register reg_;
    public:
    /* Threshold level for RX interrupts. Whilst the level of data in the RX FIFOis above this setting, the rx_threshold interrupt will be asserted. */
    zermio::BitField<0, 12, zermio::Permissions::ReadWrite> rx_thresh;
    /* Threshold level for FMT interrupts. Whilst the number of used entries in theFMT FIFO is below this setting, the fmt_threshold interrupt will be asserted. */
    zermio::BitField<16, 12, zermio::Permissions::ReadWrite> fmt_thresh;
    constexpr HostFifoConfigReg (uintptr_t addr): reg_{.addr = addr}
    {}

    inline void commit() { reg_.commit(); }

    inline HostFifoConfigReg& fetch() {
        reg_.fetch();
        return *this;
    }
};



/* Target mode FIFO configuration */
union TargetFifoConfigReg { 
    private:
      zermio::Register reg_;
    public:
    /* Threshold level for TX interrupts. Whilst the number of used entries in theTX FIFO is below this setting, the tx_threshold interrupt will be asserted. */
    zermio::BitField<0, 12, zermio::Permissions::ReadWrite> tx_thresh;
    /* Threshold level for ACQ interrupts. Whilst the level of data in the ACQ FIFOis above this setting, the acq_threshold interrupt will be asserted. */
    zermio::BitField<16, 12, zermio::Permissions::ReadWrite> acq_thresh;
    constexpr TargetFifoConfigReg (uintptr_t addr): reg_{.addr = addr}
    {}

    inline void commit() { reg_.commit(); }

    inline TargetFifoConfigReg& fetch() {
        reg_.fetch();
        return *this;
    }
};



/* Host mode FIFO status register */
union HostFifoStatusReg { 
    private:
      zermio::Register reg_;
    public:
    /* Current fill level of FMT fifo */
    zermio::BitField<0, 12, zermio::Permissions::Read> fmtlvl;
    /* Current fill level of RX fifo */
    zermio::BitField<16, 12, zermio::Permissions::Read> rxlvl;
    constexpr HostFifoStatusReg (uintptr_t addr): reg_{.addr = addr}
    {}

    inline void commit() { reg_.commit(); }

    inline HostFifoStatusReg& fetch() {
        reg_.fetch();
        return *this;
    }
};



/* Target mode FIFO status register */
union TargetFifoStatusReg { 
    private:
      zermio::Register reg_;
    public:
    /* Current fill level of TX fifo */
    zermio::BitField<0, 12, zermio::Permissions::Read> txlvl;
    /* Current fill level of ACQ fifo */
    zermio::BitField<16, 12, zermio::Permissions::Read> acqlvl;
    constexpr TargetFifoStatusReg (uintptr_t addr): reg_{.addr = addr}
    {}

    inline void commit() { reg_.commit(); }

    inline TargetFifoStatusReg& fetch() {
        reg_.fetch();
        return *this;
    }
};



/* I2C Override Control Register */
union OvrdReg { 
    private:
      zermio::Register reg_;
    public:
    /* Override the SDA and SCL TX signals. */
    zermio::BitField<0, 1, zermio::Permissions::ReadWrite> txovrden;
    /* Value for SCL Override. Set to 0 to drive TX Low, and set to 1 for high-Z */
    zermio::BitField<1, 1, zermio::Permissions::ReadWrite> sclval;
    /* Value for SDA Override. Set to 0 to drive TX Low, and set to 1 for high-Z */
    zermio::BitField<2, 1, zermio::Permissions::ReadWrite> sdaval;
    constexpr OvrdReg (uintptr_t addr): reg_{.addr = addr}
    {}

    inline void commit() { reg_.commit(); }

    inline OvrdReg& fetch() {
        reg_.fetch();
        return *this;
    }
};



/* Oversampled RX values */
union ValReg { 
    private:
      zermio::Register reg_;
    public:
    /* Last 16 oversampled values of SCL. Most recent bit is bit 0, oldest 15. */
    zermio::BitField<0, 16, zermio::Permissions::Read> scl_rx;
    /* Last 16 oversampled values of SDA. Most recent bit is bit 16, oldest 31. */
    zermio::BitField<16, 16, zermio::Permissions::Read> sda_rx;
    constexpr ValReg (uintptr_t addr): reg_{.addr = addr}
    {}

    inline void commit() { reg_.commit(); }

    inline ValReg& fetch() {
        reg_.fetch();
        return *this;
    }
};



/* Detailed I2C Timings (directly corresponding to table 10 in the I2C Specification).All values are expressed in units of the input clock period.These must be greater than 2 in order for the change in SCL to propagate to the input of the FSM so that acknowledgements are detected correctly. */
union Timing0Reg { 
    private:
      zermio::Register reg_;
    public:
    /* The actual time to hold SCL high in a given pulse.This field is sized to have a range of at least Standard Mode's 4.0 us max with a core clock at 1 GHz. */
    zermio::BitField<0, 13, zermio::Permissions::ReadWrite> thigh;
    /* The actual time to hold SCL low between any two SCL pulses.This field is sized to have a range of at least Standard Mode's 4.7 us max with a core clock at 1 GHz. */
    zermio::BitField<16, 13, zermio::Permissions::ReadWrite> tlow;
    constexpr Timing0Reg (uintptr_t addr): reg_{.addr = addr}
    {}

    inline void commit() { reg_.commit(); }

    inline Timing0Reg& fetch() {
        reg_.fetch();
        return *this;
    }
};



/* Detailed I2C Timings (directly corresponding to table 10 in the I2C Specification).All values are expressed in units of the input clock period. */
union Timing1Reg { 
    private:
      zermio::Register reg_;
    public:
    /* The nominal rise time to anticipate for the bus (depends on capacitance).This field is sized to have a range of at least Standard Mode's 1000 ns max with a core clock at 1 GHz. */
    zermio::BitField<0, 10, zermio::Permissions::ReadWrite> t_r;
    /* The nominal fall time to anticipate for the bus (influences SDA hold times).This field is sized to have a range of at least Standard Mode's 300 ns max with a core clock at 1 GHz. */
    zermio::BitField<16, 9, zermio::Permissions::ReadWrite> t_f;
    constexpr Timing1Reg (uintptr_t addr): reg_{.addr = addr}
    {}

    inline void commit() { reg_.commit(); }

    inline Timing1Reg& fetch() {
        reg_.fetch();
        return *this;
    }
};



/* Detailed I2C Timings (directly corresponding to table 10 in the I2C Specification).All values are expressed in units of the input clock period. */
union Timing2Reg { 
    private:
      zermio::Register reg_;
    public:
    /* Actual setup time for repeated start signals.This field is sized to have a range of at least Standard Mode's 4.7 us max with a core clock at 1 GHz. */
    zermio::BitField<0, 13, zermio::Permissions::ReadWrite> tsu_sta;
    /* Actual hold time for start signals.This field is sized to have a range of at least Standard Mode's 4.0 us max with a core clock at 1 GHz. */
    zermio::BitField<16, 13, zermio::Permissions::ReadWrite> thd_sta;
    constexpr Timing2Reg (uintptr_t addr): reg_{.addr = addr}
    {}

    inline void commit() { reg_.commit(); }

    inline Timing2Reg& fetch() {
        reg_.fetch();
        return *this;
    }
};



/* Detailed I2C Timings (directly corresponding to table 10, in the I2C Specification).All values are expressed in units of the input clock period. */
union Timing3Reg { 
    private:
      zermio::Register reg_;
    public:
    /* Actual setup time for data (or ack) bits.This field is sized to have a range of at least Standard Mode's 250 ns max with a core clock at 1 GHz. */
    zermio::BitField<0, 9, zermio::Permissions::ReadWrite> tsu_dat;
    /* Actual hold time for data (or ack) bits.(Note, where required, the parameters TVD_DAT is taken to be THD_DAT+T_F)This field is sized to have a range that accommodates Standard Mode's 3.45 us max for TVD_DAT with a core clock at 1 GHz.However, this field is generally expected to represent a time substantially shorter than that.It should be long enough to cover the maximum round-trip latency from output pins, through pads and voltage transitions on the board, and back to the input pins, but it should not be substantially greater. */
    zermio::BitField<16, 13, zermio::Permissions::ReadWrite> thd_dat;
    constexpr Timing3Reg (uintptr_t addr): reg_{.addr = addr}
    {}

    inline void commit() { reg_.commit(); }

    inline Timing3Reg& fetch() {
        reg_.fetch();
        return *this;
    }
};



/* Detailed I2C Timings (directly corresponding to table 10, in the I2C Specification).All values are expressed in units of the input clock period. */
union Timing4Reg { 
    private:
      zermio::Register reg_;
    public:
    /* Actual setup time for stop signals.This field is sized to have a range of at least Standard Mode's 4.0 us max with a core clock at 1 GHz. */
    zermio::BitField<0, 13, zermio::Permissions::ReadWrite> tsu_sto;
    /* Actual time between each STOP signal and the following START signal.This field is sized to have a range of at least Standard Mode's 4.7 us max with a core clock at 1 GHz. */
    zermio::BitField<16, 13, zermio::Permissions::ReadWrite> t_buf;
    constexpr Timing4Reg (uintptr_t addr): reg_{.addr = addr}
    {}

    inline void commit() { reg_.commit(); }

    inline Timing4Reg& fetch() {
        reg_.fetch();
        return *this;
    }
};



/* I2C clock stretching and bus timeout control.This timeout must be enabled by setting !!TIMEOUT_CTRL.EN to 1, and the behavior of this feature depends on the value of !!TIMEOUT_CTRL.MODE.If the mode is "STRETCH_TIMEOUT", this is used in I2C controller mode to detect whether a connected target is stretching a single low time beyond the timeout value.Configured as such, this timeout is more informative and doesn't do more than assert the "stretch_timeout" interrupt.If the mode is "BUS_TIMEOUT", it is used to detect whether the clock has been held low for too long instead, inclusive of the controller's clock low time.This is useful for an SMBus context, where the VAL programmed should be tTIMEOUT:MIN. */
union TimeoutCtrlReg { 
    private:
      zermio::Register reg_;
    public:
    /* Clock stretching timeout value (in units of input clock frequency) */
    zermio::BitField<0, 30, zermio::Permissions::ReadWrite> val;
    /* Selects the timeout mode, between a stretch timeout and a bus timeout.Between the two modes, the primary difference is how much of the clock low period is counted.For a stretch timeout, only the time that another device holds the clock low will be counted.For a bus timeout, the entire clock low time is counted, consistent with the SMBus tTIMEOUT type.!!TIMEOUT_CTRL.EN must be 1 for either of these features to be enabled. */
    zermio::BitField<30, 1, zermio::Permissions::ReadWrite> mode;
    /* Enable stretch timeout or bus timeout feature */
    zermio::BitField<31, 1, zermio::Permissions::ReadWrite> en;
    constexpr TimeoutCtrlReg (uintptr_t addr): reg_{.addr = addr}
    {}

    inline void commit() { reg_.commit(); }

    inline TimeoutCtrlReg& fetch() {
        reg_.fetch();
        return *this;
    }
};



/* I2C target address and mask pairs */
union TargetIdReg { 
    private:
      zermio::Register reg_;
    public:
    /* I2C target address number 0 */
    zermio::BitField<0, 7, zermio::Permissions::ReadWrite> address0;
    /* I2C target mask number 0.At least one bit in MASK0 must be set to 1 for ADDRESS0 to be used. */
    zermio::BitField<7, 7, zermio::Permissions::ReadWrite> mask0;
    /* I2C target address number 1 */
    zermio::BitField<14, 7, zermio::Permissions::ReadWrite> address1;
    /* I2C target mask number 1.At least one bit in MASK1 must be set to 1 for ADDRESS1 to be used. */
    zermio::BitField<21, 7, zermio::Permissions::ReadWrite> mask1;
    constexpr TargetIdReg (uintptr_t addr): reg_{.addr = addr}
    {}

    inline void commit() { reg_.commit(); }

    inline TargetIdReg& fetch() {
        reg_.fetch();
        return *this;
    }
};



/* I2C target acquired data */
union AcqdataReg { 
    private:
      zermio::Register reg_;
    public:
    /* Address for accepted transaction or acquired byte */
    zermio::BitField<0, 8, zermio::Permissions::Read> abyte;
    /* Indicates any control symbols associated with the ABYTE.For the STOP symbol, a stretch timeout or other unexpected events will cause a NACK_STOP to appear in the ACQ FIFO.If the ACQ FIFO doesn't have enough space to record a START and a STOP, the transaction will be dropped entirely on a stretch timeout.In that case, the START byte will not appear (neither as START nor NACK_START), but a standalone NACK_STOP may, if there was space.Software can discard any standalone NACK_STOP that appears.See the associated values for more information about the contents. */
    zermio::BitField<8, 3, zermio::Permissions::Read> signal;
    constexpr AcqdataReg (uintptr_t addr): reg_{.addr = addr}
    {}

    inline void commit() { reg_.commit(); }

    inline AcqdataReg& fetch() {
        reg_.fetch();
        return *this;
    }
};



/* I2C target transmit data */
union TxdataReg { 
    private:
      zermio::Register reg_;
    public:
    /*  */
    zermio::BitField<0, 8, zermio::Permissions::Write> txdata;
    constexpr TxdataReg (uintptr_t addr): reg_{.addr = addr}
    {}

    inline void commit() { reg_.commit(); }

    inline TxdataReg& fetch() {
        reg_.fetch();
        return *this;
    }
};



/* I2C host clock generation timeout value (in units of input clock frequency).In an active transaction in Target-Mode, if the Controller ceases to send SCL pulsesfor this number of cycles then the "host_timeout" interrupt will be asserted.In multi-controller monitoring mode, !!HOST_TIMEOUT_CTRL is required to be nonzero to transition out of the initial busy state.Set this CSR to 0 to disable this behaviour. */
union HostTimeoutCtrlReg { 
    private:
      zermio::Register reg_;
    public:
    /*  */
    zermio::BitField<0, 20, zermio::Permissions::ReadWrite> host_timeout_ctrl;
    constexpr HostTimeoutCtrlReg (uintptr_t addr): reg_{.addr = addr}
    {}

    inline void commit() { reg_.commit(); }

    inline HostTimeoutCtrlReg& fetch() {
        reg_.fetch();
        return *this;
    }
};



/* I2C target internal stretching timeout control.When the target has stretched beyond this time it will send a NACK for incoming data bytes or release SDA for outgoing data bytes.The behavior for the address byte is configurable via !!CTRL.ACK_ADDR_AFTER_TIMEOUT.Note that the count accumulates stretching time over the course of a transaction.In other words, this is equivalent to the SMBus cumulative target clock extension time. */
union TargetTimeoutCtrlReg { 
    private:
      zermio::Register reg_;
    public:
    /* Clock stretching timeout value (in units of input clock frequency) */
    zermio::BitField<0, 31, zermio::Permissions::ReadWrite> val;
    /* Enable timeout feature and send NACK once the timeout has been reached */
    zermio::BitField<31, 1, zermio::Permissions::ReadWrite> en;
    constexpr TargetTimeoutCtrlReg (uintptr_t addr): reg_{.addr = addr}
    {}

    inline void commit() { reg_.commit(); }

    inline TargetTimeoutCtrlReg& fetch() {
        reg_.fetch();
        return *this;
    }
};



/* Number of times the I2C target has NACK'ed a new transaction since the last read of this register.Reading this register clears it.This is useful because when the ACQ FIFO is full the software know that a NACK has occurred, but without this register would not know how many transactions it missed.When it reaches its maximum value it will stay at that value. */
union TargetNackCountReg { 
    private:
      zermio::Register reg_;
    public:
    /*  */
    zermio::BitField<0, 8, zermio::Permissions::ReadWrite> target_nack_count;
    constexpr TargetNackCountReg (uintptr_t addr): reg_{.addr = addr}
    {}

    inline void commit() { reg_.commit(); }

    inline TargetNackCountReg& fetch() {
        reg_.fetch();
        return *this;
    }
};



/* Controls for mid-transfer (N)ACK phase handling */
union TargetAckCtrlReg { 
    private:
      zermio::Register reg_;
    public:
    /* Remaining number of bytes the Target module may ACK automatically.If !!CTRL.ACK_CTRL_EN is set to 1, the Target module will stretch the clock at the (N)ACK phase of a byte if this CSR is 0, awaiting software's instructions.At the beginning of each Write transfer, this byte count is reset to 0.Writes to this CSR also are only accepted while the Target module is stretching the clock.The Target module will always ACK its address if the ACQ FIFO has space.For data bytes afterwards, it will stop at the (N)ACK phase and stretch the clock when this CSR is 0.For each data byte that is ACK'd in a transaction, the byte count will decrease by 1.Note that a full ACQ FIFO can still cause the Target module to halt at the beginning of a new byte.The ACK Control Mode provides an additional synchronization point, during the (N)ACK phase instead of after.For both cases, !!TARGET_TIMEOUT_CTRL applies, and stretching past the timeout will produce an automatic NACK.This mode can be used to implement the mid-transfer (N)ACK responses required by various SMBus protocols. */
    zermio::BitField<0, 9, zermio::Permissions::ReadWrite> nbytes;
    /* When the Target module stretches on the (N)ACK phase of a Write due to !!TARGET_ACK_CTRL.NBYTES being 0, writing a 1 here will cause it to send a NACK.If software chooses to NACK, note that the NACKing behavior is the same as if a stretch timeout occurred.The rest of the transaction will be NACK'd, including subsequent transfers.For the address byte, the (N)ACK phase of subsequent transfers will follow the behavior specified by !!CTRL.NACK_ADDR_AFTER_TIMEOUT.Automatically clears to 0. */
    zermio::BitField<31, 1, zermio::Permissions::Write> nack;
    constexpr TargetAckCtrlReg (uintptr_t addr): reg_{.addr = addr}
    {}

    inline void commit() { reg_.commit(); }

    inline TargetAckCtrlReg& fetch() {
        reg_.fetch();
        return *this;
    }
};



/* The data byte pending to be written to the ACQ FIFO.This CSR is only valid while the Target module is stretching in the (N)ACK phase, indicated by !!STATUS.ACK_CTRL_STRETCH .It is intended to be used with ACK Control Mode, so software may check the current byte. */
union AcqFifoNextDataReg { 
    private:
      zermio::Register reg_;
    public:
    /*  */
    zermio::BitField<0, 8, zermio::Permissions::Read> acq_fifo_next_data;
    constexpr AcqFifoNextDataReg (uintptr_t addr): reg_{.addr = addr}
    {}

    inline void commit() { reg_.commit(); }

    inline AcqFifoNextDataReg& fetch() {
        reg_.fetch();
        return *this;
    }
};



/* Timeout in Host-Mode for an unhandled NACK before hardware automatically ends the transaction.(in units of input clock frequency)If an active Controller-Transmitter transfer receives a NACK from the Target, the !!CONTROLLER_EVENTS.NACK bit is set.In turn, this causes the Controller FSM to halt awaiting software intervention, and the 'controller_halt' interrupt may assert.Software must clear the !!CONTROLLER_EVENTS.NACK bit to allow the state machine to continue, typically after clearing out the FMTFIFO to start a new transfer.While halted, the active transaction is not ended (no STOP (P) condition is created), and the block asserts SCL and leaves SDA released.This timeout can be used to automatically produce a STOP condition, whether as a backstop for slow software responses (longer timeout) or as a convenience (short timeout).If the timeout expires, the Controller FSM will issue a STOP (P) condition on the bus to end the active transaction.Additionally, the !!CONTROLLER_EVENTS.UNHANDLED_NACK_TIMEOUT bit is set to alert software, and the FSM will return to the idle state and halt until the bit is cleared.The enable bit must be set for this feature to operate. */
union HostNackHandlerTimeoutReg { 
    private:
      zermio::Register reg_;
    public:
    /* Unhandled NAK timeout value (in units of input clock frequency) */
    zermio::BitField<0, 31, zermio::Permissions::ReadWrite> val;
    /* Timeout enable */
    zermio::BitField<31, 1, zermio::Permissions::ReadWrite> en;
    constexpr HostNackHandlerTimeoutReg (uintptr_t addr): reg_{.addr = addr}
    {}

    inline void commit() { reg_.commit(); }

    inline HostNackHandlerTimeoutReg& fetch() {
        reg_.fetch();
        return *this;
    }
};



/* Latched events that explain why the controller halted.Any bits that are set must be written (with a 1) to clear the CONTROLLER_HALT interrupt. */
union ControllerEventsReg { 
    private:
      zermio::Register reg_;
    public:
    /* Received an unexpected NACK */
    zermio::BitField<0, 1, zermio::Permissions::ReadWrite> nack;
    /* A Host-Mode active transaction has been ended by the !!HOST_NACK_HANDLER_TIMEOUT mechanism. */
    zermio::BitField<1, 1, zermio::Permissions::ReadWrite> unhandled_nack_timeout;
    /* A Host-Mode active transaction has terminated due to a bus timeout activated by !!TIMEOUT_CTRL. */
    zermio::BitField<2, 1, zermio::Permissions::ReadWrite> bus_timeout;
    /* A Host-Mode active transaction has terminated due to lost arbitration. */
    zermio::BitField<3, 1, zermio::Permissions::ReadWrite> arbitration_lost;
    constexpr ControllerEventsReg (uintptr_t addr): reg_{.addr = addr}
    {}

    inline void commit() { reg_.commit(); }

    inline ControllerEventsReg& fetch() {
        reg_.fetch();
        return *this;
    }
};



/* Latched events that can cause the target module to stretch the clock at the beginning of a read transfer.These events cause TX FIFO-related stretching even when the TX FIFO has data available.Any bits that are set must be written (with a 1) to clear the tx_stretch interrupt.This CSR serves as a gate to prevent the Target module from responding to a read command with unrelated, leftover data. */
union TargetEventsReg { 
    private:
      zermio::Register reg_;
    public:
    /* A new Target-Mode read transfer has arrived that addressed this target.This bit is used by software to confirm the release of the contents in the TX FIFO.If the contents do not apply, software should first reset the TX FIFO, then load it with the correct data, then clear this bit.Optionally enabled by !!CTRL.TX_STRETCH_CTRL_EN. */
    zermio::BitField<0, 1, zermio::Permissions::ReadWrite> tx_pending;
    /* A Target-Mode read transfer has terminated due to a bus timeout activated by !!TIMEOUT_CTRL. */
    zermio::BitField<1, 1, zermio::Permissions::ReadWrite> bus_timeout;
    /* A Target-Mode read transfer has terminated due to lost arbitration. */
    zermio::BitField<2, 1, zermio::Permissions::ReadWrite> arbitration_lost;
    constexpr TargetEventsReg (uintptr_t addr): reg_{.addr = addr}
    {}

    inline void commit() { reg_.commit(); }

    inline TargetEventsReg& fetch() {
        reg_.fetch();
        return *this;
    }
};



/* To facilitate compiler optimization of this abstraction, prefer using this struct within a small scope.*/
struct I2c {
    IntrStateReg intr_state;
    IntrEnableReg intr_enable;
    IntrTestReg intr_test;
    CtrlReg ctrl;
    StatusReg status;
    RdataReg rdata;
    FdataReg fdata;
    FifoCtrlReg fifo_ctrl;
    HostFifoConfigReg host_fifo_config;
    TargetFifoConfigReg target_fifo_config;
    HostFifoStatusReg host_fifo_status;
    TargetFifoStatusReg target_fifo_status;
    OvrdReg ovrd;
    ValReg val;
    Timing0Reg timing0;
    Timing1Reg timing1;
    Timing2Reg timing2;
    Timing3Reg timing3;
    Timing4Reg timing4;
    TimeoutCtrlReg timeout_ctrl;
    TargetIdReg target_id;
    AcqdataReg acqdata;
    TxdataReg txdata;
    HostTimeoutCtrlReg host_timeout_ctrl;
    TargetTimeoutCtrlReg target_timeout_ctrl;
    TargetNackCountReg target_nack_count;
    TargetAckCtrlReg target_ack_ctrl;
    AcqFifoNextDataReg acq_fifo_next_data;
    HostNackHandlerTimeoutReg host_nack_handler_timeout;
    ControllerEventsReg controller_events;
    TargetEventsReg target_events;
    
    constexpr I2c (platform::I2c addr):
        intr_state(addr + 0x0), 
        intr_enable(addr + 0x4), 
        intr_test(addr + 0x8), 
        ctrl(addr + 0x10), 
        status(addr + 0x14), 
        rdata(addr + 0x18), 
        fdata(addr + 0x1c), 
        fifo_ctrl(addr + 0x20), 
        host_fifo_config(addr + 0x24), 
        target_fifo_config(addr + 0x28), 
        host_fifo_status(addr + 0x2c), 
        target_fifo_status(addr + 0x30), 
        ovrd(addr + 0x34), 
        val(addr + 0x38), 
        timing0(addr + 0x3c), 
        timing1(addr + 0x40), 
        timing2(addr + 0x44), 
        timing3(addr + 0x48), 
        timing4(addr + 0x4c), 
        timeout_ctrl(addr + 0x50), 
        target_id(addr + 0x54), 
        acqdata(addr + 0x58), 
        txdata(addr + 0x5c), 
        host_timeout_ctrl(addr + 0x60), 
        target_timeout_ctrl(addr + 0x64), 
        target_nack_count(addr + 0x68), 
        target_ack_ctrl(addr + 0x6c), 
        acq_fifo_next_data(addr + 0x70), 
        host_nack_handler_timeout(addr + 0x74), 
        controller_events(addr + 0x78), 
        target_events(addr + 0x7c){}
};


} // namespace i2c
} // namespace mmio
