
/*
 * File autogenerated by the test.
 */

#pragma once

#include  <cstdint>
namespace platform  {
/* Addresses for the devices of the type Gpio.*/
    enum Gpio: uintptr_t{Gpio = 0x80000000,GpioRpi = 0x80000010,GpioArduino = 0x80000020,GpioPmod = 0x80000030,GpioPmodc = 0x80000040,};

/* Addresses for the devices of the type Pwm.*/
    enum Pwm: uintptr_t{Pwm = 0x80001000,};

/* Addresses for the devices of the type Xadc.*/
    enum Xadc: uintptr_t{Xadc = 0x8000b000,};

/* Addresses for the devices of the type Timer.*/
    enum Timer: uintptr_t{Timer = 0x80040000,};

/* Addresses for the devices of the type Uart.*/
    enum Uart: uintptr_t{Uart0 = 0x80100000,Uart1 = 0x80101000,Uart2 = 0x80102000,};

/* Addresses for the devices of the type I2c.*/
    enum I2c: uintptr_t{I2c0 = 0x80200000,I2c1 = 0x80201000,};

/* Addresses for the devices of the type Spi.*/
    enum Spi: uintptr_t{SpiLcd = 0x80300000,SpiEthmac = 0x80301000,Spi0 = 0x80302000,Spi1 = 0x80303000,Spi2 = 0x80304000,};

enum Interrupt: uintptr_t{};
} // namespace platform

