
/*
 * File autogenerated by the test.
 */

#pragma once
/* The `platform.hh` should be created and include the specific platform header which will contain the device addresses.*/
#include  "platform.hh" 
#include  "mmio.hh" 
namespace mmio {
namespace xadc {

/*  */
union ConfigReg { 
    private:
      zermio::Register reg_;
    public:
    /*  */
    zermio::BitField<0, 1, zermio::Permissions::ReadWrite> cfg;
    constexpr ConfigReg (uintptr_t addr): reg_{.addr = addr}
    {}

    inline void commit() { reg_.commit(); }

    inline ConfigReg& fetch() {
        reg_.fetch();
        return *this;
    }
};



/*  */
union TestRegReg { 
    private:
      zermio::Register reg_;
    public:
    /*  */
    zermio::BitField<0, 1, zermio::Permissions::ReadWrite> tr;
    constexpr TestRegReg (uintptr_t addr): reg_{.addr = addr}
    {}

    inline void commit() { reg_.commit(); }

    inline TestRegReg& fetch() {
        reg_.fetch();
        return *this;
    }
};



/* To facilitate compiler optimization of this abstraction, prefer using this struct within a small scope.*/
struct Xadc {
    ConfigReg config0;
    ConfigReg config1;
    ConfigReg config2;
    TestRegReg test_reg0;
    TestRegReg test_reg1;
    TestRegReg test_reg2;
    TestRegReg test_reg3;
    
    constexpr Xadc (platform::Xadc addr):
        config0(addr + 0x40), 
        config1(addr + 0x41), 
        config2(addr + 0x42), 
        test_reg0(addr + 0x43), 
        test_reg1(addr + 0x44), 
        test_reg2(addr + 0x45), 
        test_reg3(addr + 0x46){}
};


} // namespace xadc
} // namespace mmio
