
/*
 * This file is autogenerated by the tool reismmio.
 */

#pragma once

#include  <cstdint>
namespace platform  {
/* Addresses for the devices of the type I2c.*/
    enum I2c: uintptr_t{I2c0 = 0x80200000,I2c1 = 0x80200100,};

/* Addresses for the devices of the type Timer.*/
    enum Timer: uintptr_t{Timer0 = 0x80040000,Timer1 = 0x80400100,};

enum Interrupt: uintptr_t{I2c0EventIrq = 2,I2c0ErrorIrq = 3,I2c1EventIrq = 3,Timer0FinishIrq = 10,Timer1FinishIrq = 10,};
} // namespace platform

