
/*
 * This file is autogenerated by the tool reismmio.
 */

#pragma once

#include  <cstdint>
namespace platform  {
/* Addresses for the devices of the type I2c.*/
    enum I2c: uintptr_t{I2c0 = 0x80200000,I2c1 = 0x80200100,};

/* Addresses for the devices of the type Timer.*/
    enum Timer: uintptr_t{Timer0 = 0x80040000,Timer1 = 0x80400100,};

} // namespace platform

