// Copyright (c) 2025 Douglas Reis.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

pub mod cpp;

static FILE_HEADER: &str = r#"
/*
 * This file is autogenerated by the tool zermio.
 */
"#;
