
/*
 * File autogenerated by the test.
 */

//zermio


//! These are the registers present in the gpio 
//! | Register name      | Description  | Offset | Write | Read| 
//! | :---               | :---         | :---   | :--   | :-- |
//! | OUT |  | 0x0 | true |false |
//! | IN |  | 0x4 | false |true |
//! | IN_DBNC |  | 0x8 | false |true |
//! | OUTPUT_ENABLE |  | 0xc | true |true |

use super::zermio;
/// ``` rust
/// gpio.out.update(|out| {
///     if out.pins().read() == 1 {
///        out.pins().write(0);
///     }
/// });
/// ```
pub struct Gpio {
    ///   
    pub out : out::Out,
    ///   
    pub in : in::In,
    ///   
    pub in_dbnc : in_dbnc::InDbnc,
    ///   
    pub output_enable : output_enable::OutputEnable,
}

impl Gpio {
    pub fn new(instance: u32) -> Self {
    let addr = instance as u32;
      Self {
        out : out::Out::new(addr + 0x0 ),
        in : in::In::new(addr + 0x4 ),
        in_dbnc : in_dbnc::InDbnc::new(addr + 0x8 ),
        output_enable : output_enable::OutputEnable::new(addr + 0xc ),
      }
  }
}



/// .  
pub use self::out::*;
mod out {

  use super::*;

  /// # OUT fields.  
  /// | Field name      | Description  | Offset | Write | Read| 
  /// | :---               | :---         | :---   | :--   | :-- |
  /// | PINS | Pins. | [31:0] | true |false |
  pub struct Out {
    reg: zermio::Register<u32>,
  }

  impl Out {
    pub fn new(addr: u32) -> Self {
      Self {
        reg: zermio::Register::<u32>::new(addr as usize),
      }
    }
  /// Hardware description: Pins.
  ///
  /// Returns a BitField with Write permissions, providing the following functions:
  /// | Method                | Description                                     |
  /// | :---                  | :---                                            |
  /// | **`write(val)`**      | Writes a multi-bit `val` to the field.          |
  /// | **`clear()`**         | Sets all bits in the field to 0.                |
  /// | **`write_mask(val)`** | Sets only the bits that are high (1) in `val`.  |
  /// | **`mask()`**          | Returns the bitmask for this field.             |
  /// | **`max()`**           | Returns the maximum value this field can hold.  |
  ///
    pub fn pins(&mut self) -> PinsField {
        PinsField::new(&mut self.reg)
    }

    /// Run a store instruction to write the MMIO
    pub fn commit(&mut self) {
      self.reg.commit()
    }
    /// Call action to update the inner self, then run a store instruction to write it to the MMIO
    pub fn write<F>(&mut self, action: F)
    where
      F: FnOnce(&mut Self),
    {
      action(self);
      self.reg.commit();
    }
  }
  type PinsField<'a> = zermio::BitField<'a, 0, 32, u32, zermio::access::Write>;
}



/// .  
pub use self::in::*;
mod in {

  use super::*;

  /// # IN fields.  
  /// | Field name      | Description  | Offset | Write | Read| 
  /// | :---               | :---         | :---   | :--   | :-- |
  /// | PINS | Pins. | [31:0] | false |true |
  pub struct In {
    reg: zermio::Register<u32>,
  }

  impl In {
    pub fn new(addr: u32) -> Self {
      Self {
        reg: zermio::Register::<u32>::new(addr as usize),
      }
    }
  /// Hardware description: Pins.
  ///
  /// Returns a BitField with Read permissions, providing the following functions:
  /// | Method                | Description                                     |
  /// | :---                  | :---                                            |
  /// | **`get()`**           | Returns the current value of the field.         |
  /// | **`mask()`**          | Returns the bitmask for this field.             |
  /// | **`max()`**           | Returns the maximum value this field can hold.  |
  ///
    pub fn pins(&mut self) -> PinsField {
        PinsField::new(&mut self.reg)
    }

    /// Run a load instruction to read from MMIO
    pub fn fetch(&mut self) -> &mut Self {
      self.reg.fetch();
      self
    }
  }
  type PinsField<'a> = zermio::BitField<'a, 0, 32, u32, zermio::access::Read>;
}



/// .  
pub use self::in_dbnc::*;
mod in_dbnc {

  use super::*;

  /// # IN_DBNC fields.  
  /// | Field name      | Description  | Offset | Write | Read| 
  /// | :---               | :---         | :---   | :--   | :-- |
  /// | PINS | DBNC. | [31:0] | false |true |
  pub struct InDbnc {
    reg: zermio::Register<u32>,
  }

  impl InDbnc {
    pub fn new(addr: u32) -> Self {
      Self {
        reg: zermio::Register::<u32>::new(addr as usize),
      }
    }
  /// Hardware description: DBNC.
  ///
  /// Returns a BitField with Read permissions, providing the following functions:
  /// | Method                | Description                                     |
  /// | :---                  | :---                                            |
  /// | **`get()`**           | Returns the current value of the field.         |
  /// | **`mask()`**          | Returns the bitmask for this field.             |
  /// | **`max()`**           | Returns the maximum value this field can hold.  |
  ///
    pub fn pins(&mut self) -> PinsField {
        PinsField::new(&mut self.reg)
    }

    /// Run a load instruction to read from MMIO
    pub fn fetch(&mut self) -> &mut Self {
      self.reg.fetch();
      self
    }
  }
  type PinsField<'a> = zermio::BitField<'a, 0, 32, u32, zermio::access::Read>;
}



/// .  
pub use self::output_enable::*;
mod output_enable {

  use super::*;

  /// # OUTPUT_ENABLE fields.  
  /// | Field name      | Description  | Offset | Write | Read| 
  /// | :---               | :---         | :---   | :--   | :-- |
  /// | PINS | val | [31:0] | true |true |
  pub struct OutputEnable {
    reg: zermio::Register<u32>,
  }

  impl OutputEnable {
    pub fn new(addr: u32) -> Self {
      Self {
        reg: zermio::Register::<u32>::new(addr as usize),
      }
    }
  /// Hardware description: val
  ///
  /// Returns a BitField with ReadWrite permissions, providing the following functions:
  /// | Method                | Description                                     |
  /// | :---                  | :---                                            |
  /// | **`get()`**           | Returns the current value of the field.         |
  /// | **`write(val)`**      | Writes a multi-bit `val` to the field.          |
  /// | **`clear()`**         | Sets all bits in the field to 0.                |
  /// | **`write_mask(val)`** | Sets only the bits that are high (1) in `val`.  |
  /// | **`mask()`**          | Returns the bitmask for this field.             |
  /// | **`max()`**           | Returns the maximum value this field can hold.  |
  ///
    pub fn pins(&mut self) -> PinsField {
        PinsField::new(&mut self.reg)
    }

    /// Run a load instruction to read from MMIO
    pub fn fetch(&mut self) -> &mut Self {
      self.reg.fetch();
      self
    }
    /// Run a store instruction to write the MMIO
    pub fn commit(&mut self) {
      self.reg.commit()
    }
    /// Call action to update the inner self, then run a store instruction to write it to the MMIO
    pub fn write<F>(&mut self, action: F)
    where
      F: FnOnce(&mut Self),
    {
      action(self);
      self.reg.commit();
    }
    /// Run a load instruction to read from the MMIO, call action, then run a store instruction 
    /// to write it to the MMIO
    pub fn update<F>(&mut self, action: F)
    where
        F: FnOnce(&mut Self),
    {
      self.reg.fetch();
      self.write(action);
    }
  }
  type PinsField<'a> = zermio::BitField<'a, 0, 32, u32, zermio::access::ReadWrite>;
}
