
/*
 * File autogenerated by the test.
 */


use super::gpio;
use super::pwm;
use super::xadc;
use super::timer;
use super::uart;
use super::i2c;
use super::spi;

pub enum GpioOffset{
  Gpio = 0x80000000,
  GpioRpi = 0x80000010,
  GpioArduino = 0x80000020,
  GpioPmod = 0x80000030,
  GpioPmodc = 0x80000040,
}

pub enum PwmOffset{
  Pwm = 0x80001000,
}

pub enum XadcOffset{
  Xadc = 0x8000b000,
}

pub enum TimerOffset{
  Timer = 0x80040000,
}

pub enum UartOffset{
  Uart0 = 0x80100000,
  Uart1 = 0x80101000,
  Uart2 = 0x80102000,
}

pub enum I2cOffset{
  I2c0 = 0x80200000,
  I2c1 = 0x80201000,
}

pub enum SpiOffset{
  SpiLcd = 0x80300000,
  SpiEthmac = 0x80301000,
  Spi0 = 0x80302000,
  Spi1 = 0x80303000,
  Spi2 = 0x80304000,
}


pub enum Interrupt{
}

#[unsafe(no_mangle)]
static mut DEVICE_PERIPHERALS: bool = false;

pub struct Peripherals {
  pub gpio: gpio::Gpio,
  pub gpio_rpi: gpio::Gpio,
  pub gpio_arduino: gpio::Gpio,
  pub gpio_pmod: gpio::Gpio,
  pub gpio_pmodc: gpio::Gpio,
  pub pwm: pwm::Pwm,
  pub xadc: xadc::Xadc,
  pub timer: timer::Timer,
  pub uart0: uart::Uart,
  pub uart1: uart::Uart,
  pub uart2: uart::Uart,
  pub i2c0: i2c::I2c,
  pub i2c1: i2c::I2c,
  pub spi_lcd: spi::Spi,
  pub spi_ethmac: spi::Spi,
  pub spi0: spi::Spi,
  pub spi1: spi::Spi,
  pub spi2: spi::Spi,}

impl Peripherals {
  #[inline]
  pub fn take() -> Option<Self> {
    //TODO: Critical section
    if unsafe { DEVICE_PERIPHERALS } {
        return None;
    }
    Some(unsafe { Peripherals::steal() })
  }
  #[inline]
  pub unsafe fn steal() -> Self {
    unsafe{DEVICE_PERIPHERALS = true;};
    Self {
        gpio: gpio::Gpio::new(GpioOffset::Gpio as u32),
        gpio_rpi: gpio::Gpio::new(GpioOffset::GpioRpi as u32),
        gpio_arduino: gpio::Gpio::new(GpioOffset::GpioArduino as u32),
        gpio_pmod: gpio::Gpio::new(GpioOffset::GpioPmod as u32),
        gpio_pmodc: gpio::Gpio::new(GpioOffset::GpioPmodc as u32),
        pwm: pwm::Pwm::new(PwmOffset::Pwm as u32),
        xadc: xadc::Xadc::new(XadcOffset::Xadc as u32),
        timer: timer::Timer::new(TimerOffset::Timer as u32),
        uart0: uart::Uart::new(UartOffset::Uart0 as u32),
        uart1: uart::Uart::new(UartOffset::Uart1 as u32),
        uart2: uart::Uart::new(UartOffset::Uart2 as u32),
        i2c0: i2c::I2c::new(I2cOffset::I2c0 as u32),
        i2c1: i2c::I2c::new(I2cOffset::I2c1 as u32),
        spi_lcd: spi::Spi::new(SpiOffset::SpiLcd as u32),
        spi_ethmac: spi::Spi::new(SpiOffset::SpiEthmac as u32),
        spi0: spi::Spi::new(SpiOffset::Spi0 as u32),
        spi1: spi::Spi::new(SpiOffset::Spi1 as u32),
        spi2: spi::Spi::new(SpiOffset::Spi2 as u32),}
  }
}
